package businessLogic;

import dao.ApartmentDAO;
import dao.RoomDAO;
import domainModel.Accommodation;
import domainModel.Apartment;
import domainModel.Room;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;

public class AccommodationHandler {
    // This method helps the user create a new accommodation, passing in input whether it is a room or an apartment
    // This class is a singleton
    private static AccommodationHandler instance = null;
    private final ApartmentDAO apartmentDAO;
    private final RoomDAO roomDAO;

    private AccommodationHandler(ApartmentDAO apartmentDAO, RoomDAO roomDAO) {
        this.apartmentDAO = apartmentDAO;
        this.roomDAO = roomDAO;
    }

    public static AccommodationHandler getInstance(ApartmentDAO apartmentDAO, RoomDAO roomDAO) {
        if (instance == null) {
            instance = new AccommodationHandler(apartmentDAO, roomDAO);
        }
        return instance;
    }

    public boolean createAccommodation(String type, String description, int maxGuestsAllowed) {
        if (type.equals("apartment")) {
            // id will be automatically generated by the database
            Apartment apartment = new Apartment(-1, description, maxGuestsAllowed);
            try {
                apartmentDAO.insert(apartment);
            } catch (Exception e) {
                System.err.println("ERROR: Could not insert apartment.");
                return false;
            }
            return true;
        } else if (type.equals("room")) {
            Room room = new Room(-1, description, maxGuestsAllowed);
            try {
                roomDAO.insert(room);
            } catch (Exception e) {
                System.err.println("ERROR: Could not insert room.");
                return false;
            }
            return true;
        } else {
            System.err.println("ERROR: Invalid accommodation type.");
            return false;
        }
    }

    public boolean removeAccommodation(int id) {
        // Check if the given id is referred to an apartment or a room (each is unique)
        try {
            apartmentDAO.delete(id);
        } catch (Exception e) {
            try {
                roomDAO.delete(id);
            } catch (Exception e2) {
                System.err.println("ERROR: Could not delete accommodation.");
                return false;
            }
        }
        return true;
    }

    public ArrayList<Apartment> getAllApartments() {
        ArrayList<Apartment> apartments;
        try {
            apartments = new ArrayList<>(apartmentDAO.getAll());
        } catch (Exception e) {
            System.err.println("ERROR: Could not get all accommodations.");
            return null;
        }
        return apartments;
    }

    public ArrayList<Room> getAllRooms() {
        ArrayList<Room> rooms;
        try {
            rooms = new ArrayList<>(roomDAO.getAll());
        } catch (Exception e) {
            System.err.println("ERROR: Could not get all accommodations.");
            return null;
        }
        return rooms;
    }

}
